name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build with Gradlea
#        run: ./gradlew build
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.4.0
        # with:
          # Arguments for the Google Java Format executable
          # args: # optional, default is --replace
          # Pattern to match files to be formatted
          # files: # optional, default is **/*.java
          # Set to true to not commit the changes
          # skipCommit: # optional, default is false
          # Version of Google Java Format to use
          # version: # optional
          # Recommended on MacOS machines
          # githubToken: # optional
          # Commit message
          # commitMessage: # optional, default is Google Java Format
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.3.1
        # with:
          # GITHUB_TOKEN.
          # github_token: # optional, default is ${{ github.token }}
          # Report level for reviewdog [info,warning,error]
          # level: # optional, default is info
          # Reporter of reviewdog command [github-pr-check,github-pr-review]
          # reporter: # optional, default is github-pr-check
          # Filtering for the reviewdog command [added,diff_context,file,nofilter].Default is `added`.
          # filter_mode: # optional, default is added
          # Exit code for reviewdog when errors are found [true,false].Default is `false`.
          # fail_on_error: # optional, default is false
          # Checkstyle config file
          # checkstyle_config: # default is google_checks.xml
          # Working directory relative to the root directory.
          # workdir: # optional, default is .
          # Tool name to use for reviewdog reporter
          # tool_name: # optional, default is reviewdog
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleRelease"
#      - name: Change Gradlew Permission
#        run:
#          chmod +x ./gradlew
#          |
#          chmod +x app/build/outputs/apk/release/signingKey.jks
#      - name: "Sign Android release"
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
